name: Generate documentation
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: hoijui/nim-ci:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate docs
        run: |
           nim doc --project --index:on rangequeries.nim
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: htmldocs